#!/usr/bin/env bash
set -euo pipefail

make fmt
CGO_ENABLED=0 go vet $(CGO_ENABLED=0 go list ./... | grep -v '/frontend/node_modules/')
golangci-lint run --allow-parallel-runners ./cmd/... ./internal/... ./pkg/...
npm --prefix frontend run lint
npm --prefix frontend run format:check
npm --prefix frontend run build
gitleaks protect --staged --redact
